[build]
  publish = "public"
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

# Настройки для предотвращения прерывания сессий
[functions]
  timeout = 30

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/employer-dashboard"
  to = "/employer-dashboard.html"
  status = 200

[[redirects]]
  from = "/agency-dashboard"
  to = "/agency-dashboard.html"
  status = 200

[[redirects]]
  from = "/admin-dashboard"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/test-demo.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Увеличиваем таймаут сессии
    Keep-Alive = "timeout=300, max=1000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 