name: Auto Commit Changes

on:
  workflow_run:
    workflows: ["Random Programming Quote Badge"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Используем токен с правами записи
          token: ${{ secrets.GITHUB_TOKEN || github.token }}
          fetch-depth: 0
          
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Commit and Push Changes
        run: |
          # Проверяем есть ли изменения
          if git status --porcelain | grep .; then
            git add .
            git commit -m "chore: auto-commit changes from workflow" || echo "No changes to commit"
            
            # Определяем текущую ветку
            CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            git push origin $CURRENT_BRANCH || echo "Failed to push to $CURRENT_BRANCH"
          else
            echo "No changes detected"
          fi