name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint || true
      - name: Unit tests
        run: npm run test:unit
      - name: E2E tests
        run: npm run test:e2e
      - name: Build
        run: npm run build
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/master'
        run: npm run deploy:staging
      - name: Notify Sentry
        if: success()
        run: |
          curl https://sentry.io/api/hooks/release/builtin/123456789/abcdef/ -X POST -H 'Content-Type: application/json' -d '{"version": "${{ github.sha }}"}'
      - name: Deploy to Production (manual)
        if: github.event_name == 'workflow_dispatch'
        run: npm run deploy:prod
