name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      force:
        description: 'Force deploy (skip tests)'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    name: Manual Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if not forced)
      if: ${{ !github.event.inputs.force }}
      run: npm test
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to ${{ github.event.inputs.environment }}
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT_ID }}"
        else
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_STAGING_PROJECT_ID }}"
        fi
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Ручной деплой на ${{ github.event.inputs.environment }} успешно завершен!"
        else
          echo "❌ Ошибка ручного деплоя на ${{ github.event.inputs.environment }}!"
        fi 