name: 🔐 Secure Firebase Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 🔍 Check for exposed secrets
        run: |
          echo "🔍 Проверяем на утечку секретов..."
          if grep -r "AIzaSyAo34JvPwyqjwzjhd-d-qEKh7HqAAWsIiM" public/; then
            echo "⚠️  Обнаружен старый API ключ!"
            exit 1
          fi
          echo "✅ Секреты не обнаружены"

  deploy:
    needs: security-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 📦 Install dependencies
        run: npm install
        
      - name: 🔐 Replace API key with environment variable
        run: |
          echo "🔐 Заменяем API ключ на переменную окружения..."
          sed -i 's/AIzaSyBQBIE0lphKrKyq40dGmv3zDACVnJL90Z0/\${{ secrets.FIREBASE_API_KEY }}/g' public/js/firebase-config.js
          echo "✅ API ключ заменен"
          
      - name: 🔥 Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: workincz-759c7
          channelId: live
          
      - name: ✅ Deploy success
        run: |
          echo "🎉 Деплой завершен успешно!"
          echo "🌐 Сайт доступен по адресу: https://workincz-759c7.web.app" 