name: 🔐 Secure Firebase Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 🔍 Check for exposed secrets
        run: |
          echo "🔍 Проверяем на утечку секретов..."
          if grep -r "AIzaSy" public/; then
            echo "⚠️  Обнаружены потенциальные API ключи!"
            exit 1
          fi
          echo "✅ Секреты не обнаружены"

  deploy:
    needs: security-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 🔐 Replace API Key with environment variable
        run: |
          echo "🔐 Заменяем API ключ на переменную окружения..."
          sed -i 's/AIzaSyAo34JvPwyqjwzjhd-d-qEKh7HqAAWsIiM/${{ secrets.FIREBASE_API_KEY }}/g' public/js/firebase-config.js
          echo "✅ API ключ заменен"
          
      - name: 🔥 Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: workincz-759c7
          channelId: live
          
      - name: 📊 Deploy Status
        run: |
          echo "🚀 Деплой завершен!"
          echo "🌐 Сайт: https://workincz-759c7.web.app"
          echo "🔐 API ключ защищен переменной окружения" 