name: Security Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 1' # Каждый понедельник в 2:00

env:
  NODE_VERSION: '18'

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: |
        echo "Запуск проверки безопасности npm пакетов..."
        mkdir -p .github/security
        npm audit --json > .github/security/npm-audit.json || true
      continue-on-error: true
      
    - name: Check for known vulnerabilities
      run: |
        if npm audit --audit-level=high; then
          echo "✅ Безопасность проверена"
        else
          echo "⚠️ Обнаружены уязвимости высокого уровня"
          echo "Детали сохранены в артефакт security-results"
          # Не прерываем workflow ошибкой, чтобы увидеть результаты CodeQL
          # exit 1
        fi
      continue-on-error: true
        
    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        queries: security-extended
      continue-on-error: true
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
      
    - name: Upload security results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-results
        path: |
          .github/security/
          .github/codeql/ 